const CONFIG={owner:"mitchrsmitc",repo:"script-nexus",branch:"main",manifest:"scripts/manifest.json"};
let scripts=[],active="All",selected=null;const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
$("#githubLink").href=`https://github.com/${CONFIG.owner}/${CONFIG.repo}`;$("#owner").value=CONFIG.owner;$("#repo").value=CONFIG.repo;
async function loadLibrary(){try{const r=await fetch(`${CONFIG.manifest}?v=${Date.now()}`);if(!r.ok)throw Error("manifest unavailable");scripts=await r.json()}catch(e){scripts=[]}renderFilters();render()}
function renderFilters(){const cats=["All",...new Set(scripts.map(s=>s.category))];$("#filters").innerHTML=cats.map(c=>`<button class="${c===active?'active':''}">${escapeHtml(c)}</button>`).join("");$$('#filters button').forEach(b=>b.onclick=()=>{active=b.textContent;renderFilters();render()})}
function render(){const q=$("#search").value.toLowerCase();const found=scripts.filter(s=>(active==='All'||s.category===active)&&`${s.title} ${s.description} ${s.language} ${s.category}`.toLowerCase().includes(q));$("#cards").innerHTML=found.map(s=>`<article class="card"><div class="icon">&gt;_</div><span class="pill">${escapeHtml(s.language)}</span><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.description)}</p><footer><span>${escapeHtml(s.category)}</span><button data-id="${escapeHtml(s.id)}">Inspect ↗</button></footer></article>`).join('');$("#empty").hidden=found.length>0;$("#scriptCount").textContent=scripts.length;$("#categoryCount").textContent=new Set(scripts.map(s=>s.category)).size;$$('[data-id]').forEach(b=>b.onclick=()=>openViewer(scripts.find(s=>s.id===b.dataset.id)))}
async function openViewer(s){selected=s;$("#viewTitle").textContent=s.title;$("#viewFile").textContent=s.path;$("#viewMeta").textContent=`${s.language} · ${s.category}`;$("#viewCode").textContent='Loading…';$("#rawLink").href=`https://github.com/${CONFIG.owner}/${CONFIG.repo}/blob/${CONFIG.branch}/${s.path}`;$("#viewer").hidden=false;try{const r=await fetch(s.path+`?v=${Date.now()}`);if(!r.ok)throw Error('Could not load script');$("#viewCode").textContent=await r.text()}catch(e){$("#viewCode").textContent=e.message}}
function openAdmin(){$("#admin").hidden=false}$("#adminOpen").onclick=openAdmin;$("#heroAdd").onclick=openAdmin;$("#search").oninput=render;$("#menu").onclick=()=>$("nav").classList.toggle('mobile');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).hidden=true);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.hidden=true});$("#copy").onclick=async e=>{await navigator.clipboard.writeText($("#viewCode").textContent);e.target.textContent='Copied ✓';setTimeout(()=>e.target.textContent='Copy',1200)};
$("#publishForm").onsubmit=async e=>{e.preventDefault();const status=$("#publishStatus"),button=$("#publishButton");status.className='publish-status';status.textContent='Preparing files…';button.disabled=true;try{const owner=$("#owner").value.trim(),repo=$("#repo").value.trim(),branch=$("#branch").value.trim(),token=$("#token").value.trim(),file=$("#file").files[0];if(!file)throw Error('Choose a script file.');const category=slug($("#category").value),filename=safeFilename(file.name),path=`scripts/${category}/${filename}`,content=await file.text();const base={owner,repo,branch,token};status.textContent='Uploading script…';await putFile({...base,path,text:content,message:`Add ${file.name}`});status.textContent='Updating library index…';let manifest=[];try{manifest=await apiGetJson({...base,path:CONFIG.manifest})}catch(err){if(err.status!==404)throw err}const id=`${Date.now()}-${slug($("#title").value)}`;manifest.push({id,title:$("#title").value.trim(),description:$("#description").value.trim(),language:$("#language").value.trim(),category:$("#category").value.trim(),path});await putFile({...base,path:CONFIG.manifest,text:JSON.stringify(manifest,null,2)+'\n',message:`Index ${file.name}`});status.textContent='Published. GitHub Pages may take a short time to refresh.';CONFIG.owner=owner;CONFIG.repo=repo;CONFIG.branch=branch;scripts=manifest;renderFilters();render();e.target.reset();$("#owner").value=owner;$("#repo").value=repo;$("#branch").value=branch}catch(err){status.className='publish-status error';status.textContent=err.message||'Publishing failed.'}finally{button.disabled=false}}
async function apiGet({owner,repo,branch,token,path}){const r=await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path}?ref=${encodeURIComponent(branch)}`,{headers:headers(token)});if(!r.ok){const x=await r.json().catch(()=>({}));const e=Error(x.message||`GitHub returned ${r.status}`);e.status=r.status;throw e}return r.json()}
async function apiGetJson(o){const x=await apiGet(o);return JSON.parse(decodeBase64(x.content.replace(/\n/g,'')))}
async function putFile(o){let sha;try{sha=(await apiGet(o)).sha}catch(e){if(e.status!==404)throw e}const body={message:o.message,content:encodeBase64(o.text),branch:o.branch};if(sha)body.sha=sha;const r=await fetch(`https://api.github.com/repos/${encodeURIComponent(o.owner)}/${encodeURIComponent(o.repo)}/contents/${o.path}`,{method:'PUT',headers:headers(o.token),body:JSON.stringify(body)});if(!r.ok){const x=await r.json().catch(()=>({}));throw Error(x.message||`Upload failed (${r.status})`)}return r.json()}
function headers(token){return{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'}}function encodeBase64(s){const bytes=new TextEncoder().encode(s);let b='';bytes.forEach(x=>b+=String.fromCharCode(x));return btoa(b)}function decodeBase64(s){const b=atob(s),a=Uint8Array.from(b,c=>c.charCodeAt(0));return new TextDecoder().decode(a)}function slug(s){return s.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'uncategorised'}function safeFilename(s){return s.replace(/[^a-zA-Z0-9._-]/g,'-')}function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}loadLibrary();
